version: '3.3'

services:
   vonk-server:
      image: simplifier/vonk
      ports:
        - "8080:4080"
      environment:
        - VONK_Repository=SQLite
        - VONK_Administration:Repository=SQLite
        - VONK_License:LicenseFile=./license/firelyserver-trial-license.json
      volumes:
        - .:/app/license
#   app:
#     name: vonk.server
#     image: simplifier/vonk:latest
#     volumes:
#       - %CD%/firelyserver-license.json:/app/firelyserver-license.json
#     env_file: .env
#     ports:
#       - 8080:4080
#     depends_on:
#       - db
#   db:
#     image: mariadb
#     environment:
#       - MYSQL_RANDOM_ROOT_PASSWORD=yes
#       - MYSQL_USER=firefly
#       - MYSQL_PASSWORD=secret_firefly_password
#       - MYSQL_DATABASE=firefly
#     volumes:
#       - firefly_iii_db:/var/lib/mysql
# volumes:
#    firefly_iii_upload:
#    firefly_iii_db:

#docker run -d -p 8080:4080 --name vonk.server -v %CD%/firelyserver-license.json:/app/firelyserver-license.json simplifier/vonk